#!/usr/bin/env python3
"""Code-first Danantara agent stack.

This module provides a small local agent layer for the repo.

The recommended use is:
1. master orchestrator for routing
2. source-layer curator for enrichment and alignment
3. source-layer enrichment for tracked source-layer plans
4. decision packager for reviewable handoff artifacts
5. workflow state agent for long-running status tracking
6. repo audit gate for consistency checks

Install:
    pip install agent-framework

Environment:
    OPENAI_API_KEY or another supported provider configuration
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import subprocess
import sys
from pathlib import Path
import asyncio

ROOT = Path(__file__).resolve().parents[2]


def _run_command(args: list[str]) -> str:
    """Run a safe repo-local command and return combined output."""
    proc = subprocess.run(
        args,
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    output = (proc.stdout or "") + (proc.stderr or "")
    if not output.strip():
        output = f"(exit code {proc.returncode})"
    return output.strip()


def get_repo_status() -> str:
    """Return a short git status snapshot for the repo."""
    return _run_command(["git", "status", "--short", "--branch"])


def run_source_layer_audit() -> str:
    """Run the source-layer audit script."""
    return _run_command([sys.executable, str(ROOT / "06-scripts" / "report_source_layer_audit.py")])


def run_repo_hygiene() -> str:
    """Run the repo hygiene guard."""
    return _run_command([sys.executable, str(ROOT / "06-scripts" / "check_repo_hygiene.py")])


def generate_source_layer_enrichment_plan(focus: str = "source-layer") -> str:
    """Generate a markdown enrichment plan in the source layer.

    The tool is intentionally narrow: it only writes the repo-controlled plan
    artifact so the workflow can turn review findings into a tracked output.
    """
    audit = read_repo_file("08-sources/SOURCE_LAYER_AUDIT.md")
    status = read_repo_file("08-sources/TIER2_STATUS.md")
    backlog = read_repo_file("08-sources/19_IMPLEMENTATION_BACKLOG.md")
    roadmap = read_repo_file("09-roadmap/README.md")

    plan_path = ROOT / "08-sources" / "SOURCE_LAYER_ENRICHMENT_PLAN.md"
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    content = f"""# Source Layer Enrichment Plan

Generated: {generated_at}
Focus: {focus}

## Purpose

Convert source-layer audit findings into a tracked enrichment plan that can be
reviewed, promoted, and implemented in the repo.

## Inputs Reviewed

- `08-sources/SOURCE_LAYER_AUDIT.md`
- `08-sources/TIER2_STATUS.md`
- `08-sources/19_IMPLEMENTATION_BACKLOG.md`
- `09-roadmap/README.md`

## Current Signals

### Audit snapshot

{audit.strip()}

### Status snapshot

{status.strip()}

### Backlog snapshot

{backlog.strip()}

### Roadmap snapshot

{roadmap.strip()}

## Recommended Enrichment Moves

1. Promote any Tier 2 placeholder that now has an authenticated source.
2. Keep the workbook change request open until the missing source gap closes.
3. Update the backlog when a blocked item acquires a named owner or evidence.
4. Regenerate the audit report after every scaffold change.
5. Expand the agent layer only where it improves routing, curation, or audit.

## Candidate Follow-Up Artifacts

- `08-sources/SOURCE_LAYER_AUDIT.md`
- `08-sources/TIER2_STATUS.md`
- `08-sources/19_IMPLEMENTATION_BACKLOG.md`
- `09-roadmap/README.md`

## Notes

This plan is generated by the repo agent layer and should be reviewed before
being treated as a maintained source artifact.
"""

    plan_path.write_text(content, encoding="utf-8")
    return f"Wrote {plan_path.relative_to(ROOT).as_posix()} with focus={focus}"


def generate_decision_package(focus: str = "decision-package") -> str:
    """Generate a repo decision package from the current agent outputs."""
    audit = read_repo_file("08-sources/SOURCE_LAYER_AUDIT.md")
    enrichment = read_repo_file("08-sources/SOURCE_LAYER_ENRICHMENT_PLAN.md")
    status = read_repo_file("08-sources/TIER2_STATUS.md")
    backlog = read_repo_file("08-sources/19_IMPLEMENTATION_BACKLOG.md")
    roadmap = read_repo_file("09-roadmap/README.md")
    root_readme = read_repo_file("README.md")
    workflow = read_repo_file("10-agents/workflows/repo-agent-loop.yaml")

    package_path = ROOT / "08-sources" / "DECISION_PACKAGE.md"
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    content = f"""# Decision Package

Generated: {generated_at}
Focus: {focus}

## Purpose

Package the latest repo routing, curation, enrichment, and audit outputs into a
single reviewable artifact.

## Sources Reviewed

- `08-sources/SOURCE_LAYER_AUDIT.md`
- `08-sources/SOURCE_LAYER_ENRICHMENT_PLAN.md`
- `08-sources/TIER2_STATUS.md`
- `08-sources/19_IMPLEMENTATION_BACKLOG.md`
- `09-roadmap/README.md`
- `10-agents/workflows/repo-agent-loop.yaml`
- `README.md`

## Routing Summary

The repo agent loop should be used when a task needs route selection, source
curation, enrichment planning, and a final audit gate before handoff.

## Consolidated Signals

### Audit

{audit.strip()}

### Enrichment plan

{enrichment.strip()}

### Status

{status.strip()}

### Backlog

{backlog.strip()}

### Roadmap

{roadmap.strip()}

### Repo framing

{root_readme.strip()}

### Workflow

{workflow.strip()}

## Decision Package

1. Route the task through the repo agent loop when it touches source grounding,
   backlog closure, or workflow audit.
2. Prefer enrichment-plan updates before expanding the agent estate again.
3. Keep the source layer and roadmap in sync with any accepted change.
4. Re-run the audit and repo hygiene checks before marking a package final.

## Handoff

Use this package as the review artifact for human approval or follow-up agent
work.
"""

    package_path.write_text(content, encoding="utf-8")
    return f"Wrote {package_path.relative_to(ROOT).as_posix()} with focus={focus}"


def generate_workflow_state(focus: str = "workflow-state") -> str:
    """Generate a workflow state snapshot for the repo agent loop."""
    decision_package = read_repo_file("08-sources/DECISION_PACKAGE.md")
    enrichment = read_repo_file("08-sources/SOURCE_LAYER_ENRICHMENT_PLAN.md")
    audit = read_repo_file("08-sources/SOURCE_LAYER_AUDIT.md")
    status = read_repo_file("08-sources/TIER2_STATUS.md")
    backlog = read_repo_file("08-sources/19_IMPLEMENTATION_BACKLOG.md")
    roadmap = read_repo_file("09-roadmap/README.md")

    state_path = ROOT / "08-sources" / "WORKFLOW_STATE.md"
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")

    content = f"""# Workflow State

Generated: {generated_at}
Focus: {focus}

## Purpose

Track the current state of the repo agent loop so long-running work can resume
without rediscovering the same context.

## State Inputs

- `08-sources/DECISION_PACKAGE.md`
- `08-sources/SOURCE_LAYER_ENRICHMENT_PLAN.md`
- `08-sources/SOURCE_LAYER_AUDIT.md`
- `08-sources/TIER2_STATUS.md`
- `08-sources/19_IMPLEMENTATION_BACKLOG.md`
- `09-roadmap/README.md`

## Current State

### Decision package

{decision_package.strip()}

### Enrichment plan

{enrichment.strip()}

### Audit

{audit.strip()}

### Status

{status.strip()}

### Backlog

{backlog.strip()}

### Roadmap

{roadmap.strip()}

## Open Questions

1. Which source-layer gaps can be closed by authenticated evidence next?
2. Which backlog items can now be promoted to named owners?
3. Which workflow steps should be retained, simplified, or expanded?

## Next Checkpoint

Re-run the repo agent loop after the next source-layer or roadmap update and
refresh this state artifact.
"""

    state_path.write_text(content, encoding="utf-8")
    return f"Wrote {state_path.relative_to(ROOT).as_posix()} with focus={focus}"


def read_repo_file(relative_path: str) -> str:
    """Read a text file inside the repo root."""
    candidate = (ROOT / relative_path).resolve()
    if ROOT not in candidate.parents and candidate != ROOT:
        return "Refused: path escapes repository root."
    if not candidate.exists():
        return f"Missing file: {relative_path}"
    return candidate.read_text(encoding="utf-8")


def list_agent_files() -> str:
    """List the agent layer files."""
    agent_root = ROOT / "10-agents"
    if not agent_root.exists():
        return "Missing agent layer."
    files = sorted(
        str(path.relative_to(ROOT)).replace("\\", "/")
        for path in agent_root.rglob("*")
        if path.is_file()
    )
    return "\n".join(files)


def _chat_client():
    from agent_framework.openai import OpenAIChatClient

    return OpenAIChatClient()


def build_master_orchestrator():
    """Create the master routing agent."""
    from agent_framework import Agent

    return Agent(
        name="DanantaraMasterOrchestrator",
        client=_chat_client(),
        instructions=(
            "Route Danantara requests to the right skill chain or repo operation. "
            "Use the source-layer curator for enrichment tasks and the repo audit "
            "gate for consistency checks. Keep outputs concise, evidence-aware, "
            "and approval-aware."
        ),
        tools=[get_repo_status, list_agent_files, run_source_layer_audit, run_repo_hygiene, read_repo_file],
    )


def build_source_layer_curator():
    """Create the source-layer curator agent."""
    from agent_framework import Agent

    return Agent(
        name="SourceLayerCurator",
        client=_chat_client(),
        instructions=(
            "Curate the source layer, backlog, and roadmap. Focus on keeping "
            "08-sources, 01-registry, 09-roadmap, and the audit artifacts aligned. "
            "Prefer small, traceable updates over speculative expansion."
        ),
        tools=[get_repo_status, list_agent_files, run_source_layer_audit, read_repo_file],
    )


def build_repo_audit_gate():
    """Create the repository audit gate agent."""
    from agent_framework import Agent

    return Agent(
        name="RepoAuditGate",
        client=_chat_client(),
        instructions=(
            "Check the repo for drift and consistency issues. Use the audit script "
            "and repo hygiene guard to validate changes before they are promoted."
        ),
        tools=[get_repo_status, run_source_layer_audit, run_repo_hygiene, read_repo_file],
    )


def build_source_layer_enrichment_agent():
    """Create the source-layer enrichment agent."""
    from agent_framework import Agent

    return Agent(
        name="SourceLayerEnrichment",
        client=_chat_client(),
        instructions=(
            "Turn source-layer audit findings into a concrete enrichment plan. "
            "Prefer repo-controlled markdown artifacts and keep updates narrow, "
            "traceable, and reviewable."
        ),
        tools=[get_repo_status, run_source_layer_audit, read_repo_file, generate_source_layer_enrichment_plan],
    )


def build_decision_packager_agent():
    """Create the decision packaging agent."""
    from agent_framework import Agent

    return Agent(
        name="DecisionPackager",
        client=_chat_client(),
        instructions=(
            "Convert the current repo routing, curation, enrichment, and audit "
            "outputs into a single decision package artifact. Keep the package "
            "concise, reviewable, and suitable for human handoff."
        ),
        tools=[
            get_repo_status,
            run_source_layer_audit,
            read_repo_file,
            generate_source_layer_enrichment_plan,
            generate_decision_package,
        ],
    )


def build_workflow_state_agent():
    """Create the workflow state agent."""
    from agent_framework import Agent

    return Agent(
        name="WorkflowStateAgent",
        client=_chat_client(),
        instructions=(
            "Track the current state of the repo agent loop. Turn the latest "
            "routing, enrichment, decision, and audit outputs into a concise "
            "state artifact that supports resumption and follow-up."
        ),
        tools=[
            get_repo_status,
            run_source_layer_audit,
            read_repo_file,
            generate_decision_package,
            generate_workflow_state,
        ],
    )


def build_agent_stack() -> dict[str, object]:
    """Build the default repo agent stack."""
    return {
        "master": build_master_orchestrator(),
        "curator": build_source_layer_curator(),
        "enrichment": build_source_layer_enrichment_agent(),
        "packager": build_decision_packager_agent(),
        "state": build_workflow_state_agent(),
        "audit": build_repo_audit_gate(),
    }


def build_workflow_factory():
    """Create a workflow factory wired to the local repo agents and tools."""
    from agent_framework.declarative import WorkflowFactory

    return (
        WorkflowFactory()
        .register_agent("DanantaraMasterOrchestrator", build_master_orchestrator())
        .register_agent("SourceLayerCurator", build_source_layer_curator())
        .register_agent("SourceLayerEnrichment", build_source_layer_enrichment_agent())
        .register_agent("DecisionPackager", build_decision_packager_agent())
        .register_agent("WorkflowStateAgent", build_workflow_state_agent())
        .register_agent("RepoAuditGate", build_repo_audit_gate())
        .register_tool("generate_source_layer_enrichment_plan", generate_source_layer_enrichment_plan)
        .register_tool("generate_decision_package", generate_decision_package)
        .register_tool("generate_workflow_state", generate_workflow_state)
        .register_tool("run_source_layer_audit", run_source_layer_audit)
        .register_tool("run_repo_hygiene", run_repo_hygiene)
    )


async def main() -> int:
    parser = argparse.ArgumentParser(description="Run a Danantara repo agent locally.")
    parser.add_argument(
        "--agent",
        choices=("master", "curator", "enrichment", "packager", "state", "audit"),
        default="master",
        help="Which agent to run.",
    )
    parser.add_argument(
        "--prompt",
        required=True,
        help="Task prompt for the selected agent.",
    )
    args = parser.parse_args()

    stack = build_agent_stack()
    agent = stack[args.agent]
    result = await agent.run(args.prompt)
    print(getattr(result, "text", result))
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
